
volumes:
  postgres_data:

services:
  soulmenu.api:
    image: ${DOCKER_REGISTRY-}soulmenuapi
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
    - pgdb
    - pgadmin

  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbSoulMenu
      POSTGRES_USER: pass
      POSTGRES_PASSWORD: pass45455627
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pass -d dbSoulMenu"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pass@pass.com"
      PGADMIN_DEFAULT_USER: pass
      PGADMIN_DEFAULT_PASSWORD: pass45455627
    ports:
      - "5050:80"
    depends_on:
      - pgdb
    volumes:
    - "./servers.json:/pgadmin4/servers.json"

  zap:
    image: zaproxy/zap-stable
    command: >
      zap-api-scan.py -t http://soulmenu.api:8080/itemMenu -f openapi -r api-scan-report.html
    ports:
      - "8090:8090"
    volumes:
      - ./reports:/zap/wrk
    depends_on:
      - soulmenu.api




