apiVersion: v1
kind: Service
metadata:
  name: soulmenu-api-service
  namespace: burguerspace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: soulmenu-api
  ports:
  - name: soulmenu-api
    port: 5000        # Porta exposta pelo serviço
    targetPort: 8080  # Porta exposta pelo contêiner/pod
  type: LoadBalancer
