apiVersion: v1
kind: ConfigMap
metadata:
  name: soulmenu-api-configmap
data:
  PostgreDbSettings__PostgresConnection: "Host=pgdb-soul.cdd0lkghshno.us-east-1.rds.amazonaws.com;Port=5432;Database=pgdb-soul;Username=pass;Password=pass45455627"
