apiVersion: apps/v1
kind: Deployment
metadata:
  name: soulmenu-api-deployment
  namespace: burguerspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soulmenu-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: soulmenu-api
    spec:
      containers:
      - name: soulmenu-api
        image: lkhouri/soulmenuapi:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20