name: .NET 8 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore SoulMenu.sln

    - name: Build
      run: dotnet build SoulMenu.sln --no-restore

    - name: Run tests
      run: dotnet test SoulMenu.Tests/SoulMenu.Tests.csproj --no-build
